name: test_web
description: An app built using Flutter for web

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^1.8.1
  global_configuration: ^1.3.0
  
dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
